export const sharedRules = {
  "max-len": ["error", { code: 140, ignoreUrls: true, ignoreRegExpLiterals: true, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreComments: true }],
  "max-lines": ["error", { max: 100, skipBlankLines: true, skipComments: true }],
  "max-lines-per-function": ["error", { max: 20, skipBlankLines: true, skipComments: true }],
  "max-depth": ["error", 2],
  "complexity": ["error", 6],
  "no-magic-numbers": ["error", { ignore: [-1, 0, 1, 2], ignoreArrayIndexes: true, enforceConst: true }],
  "prefer-const": "error",
  "prefer-template": "error",
  "eqeqeq": ["error", "always"],
  "no-console": "error",
  "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
  "brace-style": ["error", "1tbs", { allowSingleLine: false }],
  "no-unused-vars": "off",
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
  "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
  "import/order": ["error", { groups: ["builtin", "external", "internal", "parent", "sibling", "index"], "newlines-between": "always", alphabetize: { order: "asc", caseInsensitive: true } }],
  "import/no-cycle": "error",
};
